#+TITLE: Key-signing export scripts
#+AUTHOR: Roger J. H. Welsh
#+EMAIL: rjhwelsh@gmail.com

These scripts are to make exporting key signatures easier.

First, check fingerprints, verify identities and sign keys.
#+BEGIN_SRC sh
gpg --sign-key --fingerprint $key_id
# OR
gpg --edit-key $key_id
gpg> fpr
gpg> sign
#+END_SRC

To export ALL of your signed keys, run:
#+BEGIN_SRC sh
./export_keys_signed_by.sh $your_key
#+END_SRC

This will export all keys you have signed to a folder.
=signed_keys/$email= for each key.

Then run your favourite email client and attach:
    - signed_key.asc :: encrypted key for recipient
    - msg.asc :: encrypted instructions for recipient

The recipient is then free to upload their signed keys to a keyserver, if they
choose to do so.

This is done by running the following on their end.
#+BEGIN_SRC sh
gpg -d signed_key.asc | gpg --import
gpg --keyserver hkp://pool.sks-keyservers.net --send-key $their_key
#+END_SRC

* Troubleshooting

** sign+encrypt failed: Unusable public key
This usually means that encryption key is unavailable for the keyid.
You will need to contact the user for their encryption key, or ask if they would
like you upload it for them to a keyserver.

Alternatively, it could mean that you do not have a signing key, and cannot
sign. If this were the case you would get this error for every key you tried to sign.
